DIR_NOTES := $(DIR_CONTENT)/notes
DIR_BUILD_FRAG_NOTES := $(DIR_BUILD_FRAG)/notes

ALL_NOTES := $(filter $(DIR_NOTES)/%,$(PAGE_METADATA_FILES))
ALL_NOTES_DIRS := $(ALL_NOTES:%/page.json=%)

ALL_NOTES_METACONTENT_DIRS := $(ALL_NOTES_DIRS:$(DIR_NOTES)/%=$(DIR_BUILD_FRAG_NOTES)/%)

ALL_NOTES_METACONTENT := $(addsuffix /sidebar.frag.html,$(ALL_NOTES_METACONTENT_DIRS)) $(addsuffix /topbar.frag.html,$(ALL_NOTES_METACONTENT_DIRS)) 

BUILD_FRAG_FILES += $(ALL_NOTES_METACONTENT)
